In [10]:
import pandas as pd

In [11]:
dataset=pd.read_csv("insurance_pre.csv")

In [12]:
dataset

      age     sex     bmi  children smoker      charges
0      19  female  27.900         0    yes  16884.92400
1      18    male  33.770         1     no   1725.55230
2      28    male  33.000         3     no   4449.46200
3      33    male  22.705         0     no  21984.47061
4      32    male  28.880         0     no   3866.85520
...   ...     ...     ...       ...    ...          ...
1333   50    male  30.970         3     no  10600.54830
1334   18  female  31.920         0     no   2205.98080
1335   18  female  36.850         0     no   1629.83350
1336   21  female  25.800         0     no   2007.94500
1337   61  female  29.070         0    yes  29141.36030

[1338 rows x 6 columns]

In [13]:
dataset=pd.get_dummies(dataset,dtype=int,drop_first=True)
dataset

      age     bmi  children      charges  sex_male  smoker_yes
0      19  27.900         0  16884.92400         0           1
1      18  33.770         1   1725.55230         1           0
2      28  33.000         3   4449.46200         1           0
3      33  22.705         0  21984.47061         1           0
4      32  28.880         0   3866.85520         1           0
...   ...     ...       ...          ...       ...         ...
1333   50  30.970         3  10600.54830         1           0
1334   18  31.920         0   2205.98080         0           0
1335   18  36.850         0   1629.83350         0           0
1336   21  25.800         0   2007.94500         0           0
1337   61  29.070         0  29141.36030         0           1

[1338 rows x 6 columns]

In [14]:
dataset.columns

Index(['age', 'bmi', 'children', 'charges', 'sex_male', 'smoker_yes'], dtype='object')

In [15]:
independent=dataset[['age', 'bmi', 'children', 'sex_male', 'smoker_yes']]
independent

      age     bmi  children  sex_male  smoker_yes
0      19  27.900         0         0           1
1      18  33.770         1         1           0
2      28  33.000         3         1           0
3      33  22.705         0         1           0
4      32  28.880         0         1           0
...   ...     ...       ...       ...         ...
1333   50  30.970         3         1           0
1334   18  31.920         0         0           0
1335   18  36.850         0         0           0
1336   21  25.800         0         0           0
1337   61  29.070         0         0           1

[1338 rows x 5 columns]

In [16]:
dependent=dataset[['charges']]
dependent

          charges
0     16884.92400
1      1725.55230
2      4449.46200
3     21984.47061
4      3866.85520
...           ...
1333  10600.54830
1334   2205.98080
1335   1629.83350
1336   2007.94500
1337  29141.36030

[1338 rows x 1 columns]

In [22]:
from sklearn.model_selection import GridSearchCV
param_grid={'scoring':['str', 'callable', 'list', 'tuple','None']}
from sklearn.tree import DecisionTreeRegressor
param_grid={'criterion':['squared_error', 'friedman_mse', 'absolute_error', 'poisson'],'splitter':['best', 'random'],
            'max_features':['auto','sqrt','log2']}

grid = GridSearchCV(DecisionTreeRegressor(),param_grid,refit=True,verbose=3,n_jobs=-1)

grid.fit(independent,dependent)

Fitting 5 folds for each of 24 candidates, totalling 120 fits

C:\Users\yashi\anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py:425: FitFailedWarning:
40 fits failed out of a total of 120.
The score on these train-test partitions for these parameters will be set to nan.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
28 fits failed with the following error:
Traceback (most recent call last):
  File "C:\Users\yashi\anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py", line 732, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "C:\Users\yashi\anaconda3\Lib\site-packages\sklearn\base.py", line 1144, in wrapper
    estimator._validate_params()
  File "C:\Users\yashi\anaconda3\Lib\site-packages\sklearn\base.py", line 637, in _validate_params
    validate_parameter_constraints(
  File "C:\Users\yashi\anaconda3\Lib\site-packages\sklearn\utils\_param_validation.py", line 95, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'max_features' parameter of DecisionTreeRegressor must be an int in the range [1, inf), a float in the range (0.0, 1.0], a str among {'log2', 'sqrt'} or None. Got 'auto' instead.

--------------------------------------------------------------------------------
12 fits failed with the following error:
Traceback (most recent call last):
  File "C:\Users\yashi\anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py", line 732, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "C:\Users\yashi\anaconda3\Lib\site-packages\sklearn\base.py", line 1144, in wrapper
    estimator._validate_params()
  File "C:\Users\yashi\anaconda3\Lib\site-packages\sklearn\base.py", line 637, in _validate_params
    validate_parameter_constraints(
  File "C:\Users\yashi\anaconda3\Lib\site-packages\sklearn\utils\_param_validation.py", line 95, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'max_features' parameter of DecisionTreeRegressor must be an int in the range [1, inf), a float in the range (0.0, 1.0], a str among {'sqrt', 'log2'} or None. Got 'auto' instead.

  warnings.warn(some_fits_failed_message, FitFailedWarning)
C:\Users\yashi\anaconda3\Lib\site-packages\sklearn\model_selection\_search.py:976: UserWarning: One or more of the test scores are non-finite: [       nan        nan 0.68971364 0.61369427 0.62494775 0.62139879
        nan        nan 0.6995127  0.67972129 0.71049278 0.61218798
        nan        nan 0.67618796 0.68910302 0.69142552 0.65445873
        nan        nan 0.68909972 0.61446977 0.69312471 0.65013181]
  warnings.warn(

GridSearchCV(estimator=DecisionTreeRegressor(), n_jobs=-1,
             param_grid={'criterion': ['squared_error', 'friedman_mse',
                                       'absolute_error', 'poisson'],
                         'max_features': ['auto', 'sqrt', 'log2'],
                         'splitter': ['best', 'random']},
             verbose=3)

In [23]:
re=grid.cv_results_
print("The R_score value for best parameter {}:".format(grid.best_params_))

The R_score value for best parameter {'criterion': 'friedman_mse', 'max_features': 'log2', 'splitter': 'best'}:

In [24]:
table=pd.DataFrame.from_dict(re)

In [25]:
table

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_criterion,param_max_features,param_splitter,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.003127,6.253719e-03,0.000000,0.000000,squared_error,auto,best,"{'criterion': 'squared_error', 'max_features':...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,17
1,0.003127,6.253719e-03,0.000000,0.000000,squared_error,auto,random,"{'criterion': 'squared_error', 'max_features':...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,17
2,0.018755,1.169632e-02,0.009379,0.007658,squared_error,sqrt,best,"{'criterion': 'squared_error', 'max_features':...",0.712130,0.603328,0.659955,0.711630,0.761524,0.689714,0.053829,5
3,0.012504,6.251812e-03,0.003126,0.006251,squared_error,sqrt,random,"{'criterion': 'squared_error', 'max_features':...",0.676092,0.493459,0.596160,0.662094,0.640667,0.613694,0.065920,15
4,0.012504,6.251860e-03,0.003126,0.006252,squared_error,log2,best,"{'criterion': 'squared_error', 'max_features':...",0.739918,0.615774,0.320536,0.737958,0.710553,0.624948,0.158788,12
5,0.003126,6.252193e-03,0.009378,0.007657,squared_error,log2,random,"{'criterion': 'squared_error', 'max_features':...",0.622512,0.539409,0.622960,0.722167,0.599945,0.621399,0.058891,13
6,0.000000,0.000000e+00,0.000000,0.000000,friedman_mse,auto,best,"{'criterion': 'friedman_mse', 'max_features': ...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,17
7,0.000000,0.000000e+00,0.000000,0.000000,friedman_mse,auto,random,"{'criterion': 'friedman_mse', 'max_features': ...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,17
8,0.006252,7.657225e-03,0.009378,0.007657,friedman_mse,sqrt,best,"{'criterion': 'friedman_mse', 'max_features': ...",0.675253,0.623067,0.756107,0.735678,0.707459,0.699513,0.046918,2
9,0.003126,6.252956e-03,0.012503,0.006251,friedman_mse,sqrt,random,"{'criterion': 'friedman_mse', 'max_features': ...",0.732319,0.603781,0.664335,0.686886,0.711285,0.679721,0.044312,8
10,0.015631,2.002716e-06,0.003125,0.006251,friedman_mse,log2,best,"{'criterion': 'friedman_mse', 'max_features': ...",0.780433,0.657045,0.660439,0.742910,0.711637,0.710493,0.047552,1
11,0.006252,7.656933e-03,0.006253,0.007658,friedman_mse,log2,random,"{'criterion': 'friedman_mse', 'max_features': ...",0.517300,0.577876,0.608098,0.591020,0.766646,0.612188,0.083070,16
12,0.003125,6.250763e-03,0.000000,0.000000,absolute_error,auto,best,"{'criterion': 'absolute_error', 'max_features'...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,17
13,0.000000,0.000000e+00,0.000000,0.000000,absolute_error,auto,random,"{'criterion': 'absolute_error', 'max_features'...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,17
14,0.034385,6.252217e-03,0.006252,0.007657,absolute_error,sqrt,best,"{'criterion': 'absolute_error', 'max_features'...",0.641234,0.654805,0.709050,0.702111,0.673739,0.676188,0.026218,9
15,0.034388,1.169659e-02,0.000000,0.000000,absolute_error,sqrt,random,"{'criterion': 'absolute_error', 'max_features'...",0.709152,0.473329,0.777431,0.720873,0.764731,0.689103,0.110897,6
16,0.040637,7.657342e-03,0.003126,0.006253,absolute_error,log2,best,"{'criterion': 'absolute_error', 'max_features'...",0.734223,0.552240,0.738113,0.704074,0.728477,0.691426,0.070593,4
17,0.025007,1.250392e-02,0.009377,0.007657,absolute_error,log2,random,"{'criterion': 'absolute_error', 'max_features'...",0.690517,0.547644,0.685535,0.647450,0.701147,0.654459,0.056399,10
18,0.000000,0.000000e+00,0.000000,0.000000,poisson,auto,best,"{'criterion': 'poisson', 'max_features': 'auto...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,17
19,0.003126,6.251431e-03,0.000000,0.000000,poisson,auto,random,"{'criterion': 'poisson', 'max_features': 'auto...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,17
20,0.081273,6.251431e-03,0.009380,0.007659,poisson,sqrt,best,"{'criterion': 'poisson', 'max_features': 'sqrt...",0.705296,0.645906,0.651388,0.718909,0.723998,0.689100,0.033635,7
21,0.034385,2.296923e-02,0.000000,0.000000,poisson,sqrt,random,"{'criterion': 'poisson', 'max_features': 'sqrt...",0.685958,0.576594,0.673408,0.683184,0.453205,0.614470,0.090274,14
22,0.015628,7.008046e-07,0.000000,0.000000,poisson,log2,best,"{'criterion': 'poisson', 'max_features': 'log2...",0.715558,0.600622,0.741697,0.707692,0.700054,0.693125,0.048331,3
23,0.009378,7.657303e-03,0.003126,0.006252,poisson,log2,random,"{'criterion': 'poisson', 'max_features': 'log2...",0.647431,0.563837,0.791316,0.651400,0.596675,0.650132,0.077777,11

In [27]:
age_input=float(input("AGE:"))
bmi_input=float(input("BMI:"))
children_input=float(input("CHILDREN:"))
sex_male_input=float(input("SEX MALE 0 OR 1:"))
smoker_yes_input=float(input("SMOKER YES 0 OR 1:"))

AGE:25
BMI:32
CHILDREN:1
SEX MALE 0 OR 1:1
SMOKER YES 0 OR 1:0

In [28]:
future_prediction=grid.predict([[age_input,bmi_input,children_input,sex_male_input,smoker_yes_input]])
print("Future_prediction={}".format(future_prediction))

Future_prediction=[3490.5491]

C:\Users\yashi\anaconda3\Lib\site-packages\sklearn\base.py:464: UserWarning: X does not have valid feature names, but DecisionTreeRegressor was fitted with feature names
  warnings.warn(